import { MenuItem } from './menuItem';

export const MENUITEMS: MenuItem[] = [
    { id: 1, 
        name: 'Coffee',
        description: 'Little better than your office coffee', 
        recipe: {
        'Coffee': 3,
        'Decaf Coffee': 0,
        'Expresso': 0,
        'Sugar': 1,
        'Cream': 1,
        'Steamed Milk': 0,
        'Foamed Milk': 0,
        'Cocoa': 0,
        'Whipped Cream': 0
    }},
    { id: 2, 
        name: 'Decaf Coffee',
        description: 'Coffee without the kick', 
        recipe: {
        'Coffee': 0,
        'Decaf Coffee': 3,
        'Expresso': 0,
        'Sugar': 1,
        'Cream': 1,
        'Steamed Milk': 0,
        'Foamed Milk': 0,
        'Cocoa': 0,
        'Whipped Cream': 0
    }},
    { id: 3,
        name: 'Caffe Latte',
        description: 'Espresso with steamed milk & foam', 
        recipe: {
        'Coffee': 0,
        'Decaf Coffee': 0,
        'Expresso': 2,
        'Sugar': 0,
        'Cream': 0,
        'Steamed Milk': 1,
        'Foamed Milk': 0,
        'Cocoa': 0,
        'Whipped Cream': 0
    }},
    { id: 4, 
        name: 'Caffe Americano', 
        description: 'Espresso & water', 
        recipe: {
        'Coffee': 0,
        'Decaf Coffee': 0,
        'Expresso': 3,
        'Sugar': 0,
        'Cream': 0,
        'Steamed Milk': 0,
        'Foamed Milk': 0,
        'Cocoa': 0,
        'Whipped Cream': 0
    }},
    { id: 5, 
        name: 'Caffe Mocha', 
        description: 'Latte with chocolate', 
        recipe: {
        'Coffee': 0,
        'Decaf Coffee': 0,
        'Expresso': 1,
        'Sugar': 0,
        'Cream': 0,
        'Steamed Milk': 1,
        'Foamed Milk': 0,
        'Cocoa': 1,
        'Whipped Cream': 1
    }},
    { id: 6, 
        name: 'Cappuccino', 
        description: 'Espresso with steamed milk & foamed milk', 
        recipe: {
        'Coffee': 0,
        'Decaf Coffee': 0,
        'Expresso': 2,
        'Sugar': 0,
        'Cream': 0,
        'Steamed Milk': 1,
        'Foamed Milk': 1,
        'Cocoa': 0,
        'Whipped Cream': 0
    }},
];